version: '3.8'
services:
  client-backend:
    image: backend:0.0.1
    build:
      dockerfile: ../Dockerfile
    ports:
      - 8080:8080
    restart: always
    depends_on:
      - db
    environment:
      SPRING_APPLICATION_JSON: '{
        "spring.datasource.url"  : "jdbc:postgresql://db:5432/$DB_NAME",
        "spring.datasource.username" : "$DB_USER",
        "spring.datasource.password" : "$DB_PASSWORD",
        "spring.jpa.hibernate.ddl-auto" : "validate",
        "application.security.jwt.secret-key" : "$JWT_SECRET_KEY",
        "application.security.jwt.expiration" : "86400000",
        "application.security.jwt.refresh-token.expiration" : "604800000"
      }'

  flyway:
    image: flyway/flyway
    command: -url=jdbc:postgresql://db/ -schemas=$DB_NAME -user=$DB_USER -password=$DB_PASSWORD -connectRetries=60 migrate
    depends_on:
      - db

  db:
    image: postgres
    restart: always
    environment:
      - POSTGRES_DB=$DB_NAME
      - POSTGRES_USER=$DB_USER
      - POSTGRES_PASSWORD=$DB_PASSWORD
    ports:
      - 5432:5432
